name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version-name:
        description: "Optional. Version string to use, in X.Y.Z format. Overrides default in the project."
        required: false
        type: string
      version-code:
        description: "Optional. Build number to use. Overrides default of GitHub run number."
        required: false
        type: number
      distribute-to-firebase:
        description: "Optional. Distribute artifacts to Firebase."
        required: false
        default: false
        type: boolean
      publish-to-play-store:
        description: "Optional. Deploy bundle artifact to Google Play Store"
        required: false
        default: false
        type: boolean

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JAVA_VERSION: 17
  GITHUB_ACTION_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # ... (previous steps remain the same up to the build step)

      - name: Build
        run: bundle exec fastlane assembleDebugApks

      # Add step to debug directory structure (optional)
      - name: List build outputs
        run: find app/build/outputs/apk -name "*.apk"

      # Updated upload steps with wildcards
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/**/release/*.apk

      - name: Upload beta APK
        uses: actions/upload-artifact@v4
        with:
          name: beta-apk
          path: app/build/outputs/apk/**/beta/*.apk

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/**/debug/*.apk

      # Updated checksum creation with wildcards
      - name: Create checksums
        run: |
          find app/build/outputs/apk -name "*.apk" -exec sha256sum {} > {}.sha256 \;

      - name: Upload checksums
        uses: actions/upload-artifact@v4
        with:
          name: apk-checksums
          path: app/build/outputs/apk/**/*.sha256
