name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version-name:
        description: "Optional. Version string to use, in X.Y.Z format. Overrides default in the project."
        required: false
        type: string
      version-code:
        description: "Optional. Build number to use. Overrides default of GitHub run number."
        required: false
        type: number
      distribute-to-firebase:
        description: "Optional. Distribute artifacts to Firebase."
        required: false
        default: false
        type: boolean
      publish-to-play-store:
        description: "Optional. Deploy bundle artifact to Google Play Store"
        required: false
        default: false
        type: boolean

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JAVA_VERSION: 17
  GITHUB_ACTION_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2

      - name: Cache Gradle files
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v2-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v2-

      - name: Cache build output
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            ${{ github.workspace }}/build-cache
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configure JDK
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Configure Ruby
        uses: ruby/setup-ruby@28c4deda893d5a96a6b2d958c5b47fc18d65c9d3 # v1.213.0
        with:
          bundler-cache: true

      - name: Install Fastlane
        run: |
          gem install bundler:2.2.27
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Check
        run: bundle exec fastlane check

      - name: Build APKs
        run: |
          bundle exec fastlane build_all_unsigned
          echo "Listing build outputs directory:"
          find app/build/outputs/apk -name "*.apk" -type f

      - name: Upload test reports on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports
          path: app/build/reports/tests/

      # Standard flavor artifacts
      - name: Upload Standard Release APK
        uses: actions/upload-artifact@v4
        with:
          name: standard-release-apk
          path: app/build/outputs/apk/standard/release/app-standard-release-unsigned.apk

      - name: Upload Standard Beta APK
        uses: actions/upload-artifact@v4
        with:
          name: standard-beta-apk
          path: app/build/outputs/apk/standard/beta/app-standard-beta-unsigned.apk

      - name: Upload Standard Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: standard-debug-apk
          path: app/build/outputs/apk/standard/debug/app-standard-debug.apk

      # F-Droid flavor artifacts
      - name: Upload F-Droid Release APK
        uses: actions/upload-artifact@v4
        with:
          name: fdroid-release-apk
          path: app/build/outputs/apk/fdroid/release/app-fdroid-release-unsigned.apk

      - name: Upload F-Droid Beta APK
        uses: actions/upload-artifact@v4
        with:
          name: fdroid-beta-apk
          path: app/build/outputs/apk/fdroid/beta/app-fdroid-beta-unsigned.apk

      - name: Upload F-Droid Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: fdroid-debug-apk
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk

      # Create checksums for all APKs
      - name: Create checksums
        run: |
          cd app/build/outputs/apk
          find . -name "*.apk" -type f -exec sh -c 'sha256sum "$1" > "$1.sha256"' sh {} \;

      # Standard flavor checksums
      - name: Upload Standard Release APK checksum
        uses: actions/upload-artifact@v4
        with:
          name: standard-release-apk-checksum
          path: app/build/outputs/apk/standard/release/app-standard-release-unsigned.apk.sha256

      - name: Upload Standard Beta APK checksum
        uses: actions/upload-artifact@v4
        with:
          name: standard-beta-apk-checksum
          path: app/build/outputs/apk/standard/beta/app-standard-beta-unsigned.apk.sha256

      - name: Upload Standard Debug APK checksum
        uses: actions/upload-artifact@v4
        with:
          name: standard-debug-apk-checksum
          path: app/build/outputs/apk/standard/debug/app-standard-debug.apk.sha256

      # F-Droid flavor checksums
      - name: Upload F-Droid Release APK checksum
        uses: actions/upload-artifact@v4
        with:
          name: fdroid-release-apk-checksum
          path: app/build/outputs/apk/fdroid/release/app-fdroid-release-unsigned.apk.sha256

      - name: Upload F-Droid Beta APK checksum
        uses: actions/upload-artifact@v4
        with:
          name: fdroid-beta-apk-checksum
          path: app/build/outputs/apk/fdroid/beta/app-fdroid-beta-unsigned.apk.sha256

      - name: Upload F-Droid Debug APK checksum
        uses: actions/upload-artifact@v4
        with:
          name: fdroid-debug-apk-checksum
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk.sha256
